### ISSUE TITLE
assembly footprint and specs

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#108]
Hello,
we have ~30x coverage ONT (N50 9.3 kb, 165 Gb) of a ~5 Gb plant genome and we would like to assemble it with Flye.
We need to estimate the resources needed: do you think that 1 TB memory will be enough? will 60-100 cores be enough to run the assembly in a decent time? (is it possible to get an estimated assembly time?) Also, how much storage space do you think we will need? Would 4 TB be enough to write intermediate files? Lastly, is the I/O speed of any importance at any step?
I see the comparison you did with human, and probably the values we have (1 TB RAM, up to 100 cores) could work. I wonder if you can tell us how to guestimate how many resources to allocate in our case.
Thanks,
Dario

**Comment by mikolmogorov** [comment]
Hi,

I think I've recently replied to one of your collaborators - here is my response so the other users can see it. 

You usually need 2-3 times more than the input size to store read alignments, so should be about 500Gb in your case. 

1Tb of RAM should be enough, but if not - consider using the `--asm-coverage` option to reduce memory usage a bit. 

I'd also suggest  not to use all 100 threads, but maybe 30-40 (because each thread uses some additional resources for local buffers). The assembly time varies for different genomes (depends on repeat content, etc) - human-like genomes with this amount of coverage take ~5000 CPUh.

Best,
Mikhail
