### ISSUE TITLE
MinOverlap value question

### ISSUE THREAD

**Issue by npavlovikj** [fenderglass/ABruijn#11]
I am running ABruijn with nanopore reads with average length of 2,000bp. Since the minimum overlap length of ABruijn must be within the [3000, 10000] range, no overlap was found for my reads, and "blasr" failed. I modified the code to accept lower overlap, and then ABruijn worked fine. With this being said, I was wondering if there are a reason why ABruijn requires such a high overlap value ?

**Comment by fenderglass** [comment]
Hi,

Generally, we consider overlaps of 2000bp as less reliable because of the overall parameter configuration - we compute "approximate" overlaps based on solid k-mers, which sometimes might lead to false matches. However, for a genome with a relatively simple structure and good data quality it might work fine.
