### ISSUE TITLE
MEMORY ISSUE?

### ISSUE THREAD

**Issue by raysully** [fenderglass/ABruijn#117]
Mikhail,

I'm trying to use flye to assemble a small bacterial genome (Micrococcus sp., ~2.5 Mb) using nanopore data called with Guppy 3.0.3.  We let the flowcell collect for 48 hrs and got something like 1000X coverage.  Flye gives me a: 

WARNING: Expected read coverage is 1042, the assembly is not guaranteed to be optimal in this setting. Are you sure that the genome size was entered correctly? 

and then ends with:

ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct

I'm unsure what the issue is.  Would you please take a look at the log and perhaps help me figure it out?

[flye.log](https://github.com/fenderglass/Flye/files/3241640/flye.log)

Thanks, Ray

**Comment by mikolmogorov** [comment]
Hi Ray,

Thanks for the detailed report. This seems weird - the log files looks ok, there are overlaps, but no disjointigs were assembled. 

It could be that solid k-mer selection went wrong. Do you think there could be contamination / technical noise on the data? I have two suggestions: first, you can try to use longest 50x reads for the initial assembly by adding `--asm-coverage 50` option. Second, you can try `--meta` option, since it is more robust to abnormal k-mer frequency distrubutions.

Let me know if this helps,
Mikhail

**Comment by raysully** [comment]
Mikhail,

It seemed to work using --asm-coverage 50. Thanks very much!  

There's 2 contigs; one very small and the other very large.  Can't wait to use your --plasmids argument!

Thanks again!

Ray

**Comment by mikolmogorov** [comment]
Glad to hear! Closing this issue for now - feel free to reopen if you have more questions.
