### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by raysully** [fenderglass/ABruijn#155]
Mikhail,

My group loves Flye!  We think it's wonderful!  It's pretty fast.  

We are getting 10-20X speed increase running Guppy on an NVIDIA 2080ti eGPU.  

Do you have any plans to add a GPU enabled Flye?  It would really make it FLYE!

Thank you, Ray

**Comment by mikolmogorov** [comment]
Hi Ray,

Thanks for the feedback!

That would be difficult, because Flye pipeline consists of multiple different steps. There is no single bottleneck (you would need to optimize every step one by one) and no standard methods for GPU translation (I assume there is plenty for neural network algorithms in Guppy). So, a lot of (unsupported) engineering work that we unfortunately don't have resources to perform.

This does not mean that we are not planning to further improve Flye performance though - just not on GPU.

Best,
Mikhail

**Comment by raysully** [comment]
Thanks, Mikhail!  Appreciate the response.
