### ISSUE TITLE
high coverage assembly

### ISSUE THREAD

**Issue by aistBMRG** [fenderglass/ABruijn#156]
Hi,

We have several deeply sequenced bacterial genomes, pacbio reads with coverage up to 500x. Would it be possible to clarify whether such high coverage be an issue? Or is it beneficial to run with such high coverage to achieve highly accurate polishing? 

Thanks! 

Dieter

**Comment by raysully** [comment]
Dieter,

Our lab has had great Flye results with 1000X (more or less) bacterial genome (ONT data) in a couple of hours using 26 threads of a 72 core cpu server using --asm-coverage 50 -i 4 --plasmids.  Hope this is helpful.  

Ray

**Comment by aistBMRG** [comment]
Great, thanks! Giving it a shot with those settings.

Dieter.

**Comment by aistBMRG** [comment]
Small update -- Using --asm-coverage 50 yielded an incomplete assembly (that is, non-circular chromosome). May I asked why you restrict the --asm-coverage, it is to reduce memory usage, or that improves assembly for your data?

Thanks.

Dieter.

**Comment by mikolmogorov** [comment]
Hi,

Reasonable `--asm-coverage` value should not affect the assmebly contiguity (but improve speed and memory consumption). It limits the coverage for draft disjointig assembly, but all reads are used during repeat resolution. Could you post / send me `assembly_graph.gv` and `assemby_info.txt` files so I can comment?

**Comment by aistBMRG** [comment]
Thanks for chiming in. I am sending the files to you by email. It would be great to understand what is going on.

Dieter.

**Comment by aistBMRG** [comment]
Please find attached the requested files; assemblies generated using --asm-coverage 50 and with --asm-coverage unset as per the default.

Regards,

Dieter

**Comment by mikolmogorov** [comment]
Hi Dieter,

Yeas, indeed it looks like the second run was better. Could you please send me the `flye.log` files from both runs to fednerglass@gmail.com? In the mean time, feel free to use the second run assemblies as the final result.

Mikhail

**Comment by mikolmogorov** [comment]
Hi Dieter, 

Thanks for sending me the logs. I think `--asm-coverage 50` is failing because for some reason a good portion of the reads has low quality (high error rate), and Flye fails to align them. As a result, instead of the desired 50x coverage, you get much less and the assembly is fragmented. You can indirectly see this by (i) Flye only aligned ~38% of reads on the graph (usually it's close to 100) and (ii) Final read alignment identity reported by minimap2 is ~20% (usually 13-14% for PacBio).

Nevertheless, there were enough good reads in your set for complete assembly (without `--asm-coverage`). Perhaps, some quality filtering might help for your future assemblies.

**Comment by aistBMRG** [comment]
Thanks for the clarification; we will QC the reads more strictly in the future.

Dieter
