### ISSUE TITLE
Understanding assembly_info.txt

### ISSUE THREAD

**Issue by dariober** [fenderglass/ABruijn#162]
Hi- Thanks a lot for the great software! I have some questions about `assembly_info.txt`. (Eventually, my aim is to figure out whether an assembly is correct and if not why, but that's another story...) 

So, about `assembly_info.txt` (attached [here](https://github.com/fenderglass/Flye/files/3686905/assembly_info.txt)):

* What is a terminal graph node (`*`)? Can it be interpreted as saying that the contig is complete?

* What does the minus sign mean in the graph path column? For example I see `contig_3 869419 22 - - 1 -99,3,-320`. Why 99 and 320 have a minus? 

Then, I aligned the sequence of the edges to the assembled genome and I'm trying to
relate the alignment results to the genome sequence and the graph.

`assembly_info.txt` tells me that contig_10 is composed of edges 193,10,435. These are the edges aligned to contig_10 (first 6 columns of SAM file):

```
edge_193  0   contig_10  2560    59  5696M
edge_10   0   contig_10  11519   60  316382M
edge_449  16  contig_10  141712  60  3114M
edge_228  16  contig_10  144826  60  9597M
edge_136  0   contig_10  170211  60  5012M
edge_287  0   contig_10  175223  60  1929M
edge_433  16  contig_10  221820  60  628M
edge_206  16  contig_10  222448  60  10239M
edge_221  0   contig_10  233576  60  7747M
edge_356  0   contig_10  250073  60  662M
edge_345  16  contig_10  255812  60  996M
edge_214  16  contig_10  263209  60  2657M
edge_464  0   contig_10  265867  60  3731M
edge_124  16  contig_10  297616  60  1334M
edge_213  16  contig_10  298950  60  12126M
edge_435  0   contig_10  327901  60  5581M
```

* The first alignment starts at position 2560. So, where do the first 2560 bases of contig_10 come from?

* There are additional edges uniquely mapped there other than 193,10,435. Am I
  right that these are redundant edges, not necessary to compose the final assembly? 

(In general, any hint to assess the quality of an assembly is most welcome!)
Thanks
Dario

**Comment by mikolmogorov** [comment]
Hi Dario,

>What is a terminal graph node

It's a node that does not have any outgoing edges, except loops. If you have a linear chromosome, this might mean that it reached the telomere. It could also mean that you have a gap / missing connection in the assembly (as opposed to an unresolved repeat).

>What does the minus sign mean in the graph path column?

Each edge is represented in to complement copies on the graph (so the graph encodes the genome and its reverse complement). Edge signs are assigned arbitrary, so they don't have any functional meaning - they could be used to locate the complement edges on the graph.

>The first alignment starts at position 2560. So, where do the first 2560 bases of contig_10 come from?

They should come from contig_10 (more specifically, from a read that aligned to contig10). It could be that the aligner failed to map a part of edge_193 - the alignment becomes difficult in repetitive regions (193 must be a repeat). A good way to check is to visualize the sequences with a dot-plot (I use gepard). Since contigs are polished after they are generated, it is possible that their length might change as well.

>There are additional edges uniquely mapped there other than 193,10,435. Am I
right that these are redundant edges, not necessary to compose the final assembly?

Yes, those must be repeats that have been resolved in this contig_10 (and edge_10). You can see that the unique edge_10 aligns all the way almost to the end of contig_10.


Best,
Mikhail
