### ISSUE TITLE
reproducibility of assemblies: 3 different results running the same dataset 3 times

### ISSUE THREAD

**Issue by michieitel** [fenderglass/ABruijn#164]
Hi!

Couldn't find a thread on this topic except for #21 which dates back to 2017, so I am opening a new issue.

I just encountered that when running Flye three times with the same settings on the same ONT dataset I get different results. Is that expected with the used algorithm? Is that because of some heuristics involved?

I was running Flye 3x each on three datasets (all reads >1kb, all >5kb, all >10kb).
The expected coverage of the three datasets were:

1kb+: ~110x
5kb+: ~80
10kb+: ~40x

I used these commands:

```
# 1kb+ repetitions
flye --threads 40 --genome-size 80m -i 2 --out-dir 1kb_run1 --nano-raw reads_porechopped.1kb.fasta.gz 2> FLYE_1kb_run1.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 1kb_run2 --nano-raw reads_porechopped.1kb.fasta.gz 2> FLYE_1kb_run2.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 1kb_run3 --nano-raw reads_porechopped.1kb.fasta.gz 2> FLYE_1kb_run3.log

# 5kb+ repetitions
flye --threads 40 --genome-size 80m -i 2 --out-dir 5kb_run1 --nano-raw reads_porechopped.5kb.fasta.gz 2> FLYE_5kb_run1.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 5kb_run2 --nano-raw reads_porechopped.5kb.fasta.gz 2> FLYE_5kb_run2.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 5kb_run3 --nano-raw reads_porechopped.5kb.fasta.gz 2> FLYE_5kb_run3.log

# 10kb+ repetitions
flye --threads 40 --genome-size 80m -i 2 --out-dir 10kb_run1 --nano-raw reads_porechopped.10kb.fasta.gz 2> FLYE_10kb_run1.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 10kb_run2 --nano-raw reads_porechopped.10kb.fasta.gz 2> FLYE_10kb_run2.log
flye --threads 40 --genome-size 80m -i 2 --out-dir 10kb_run3 --nano-raw reads_porechopped.10kb.fasta.gz 2> FLYE_10kb_run3.log

```

The stats of the raw (unpolished) assemblies are as follows:
![FLYE_stats](https://user-images.githubusercontent.com/12069446/66206549-b792e200-e6b0-11e9-9c4e-a9961ab81e16.png)

While the stats are generally more or less comparable between the runs for each dataset, it is quite striking to see such a huge difference between the longest contigs that were generated.

How one can be sure one gets the best possible assembly and how can one ensure reproducibility?

Thanks
Michael

**Comment by mikolmogorov** [comment]
Hi Michael,

Thanks for the detailed report!

Yes, some fluctuations are expected because of the heuristics. It is difficult to make Flye completely deterministic, since there is also multithreading involved, in a way that thread scheduling potentially affects the heuristics choices.

On the other hand, the statistics from multiple runs seem mostly consistent to me. Largest contig is not a very robust measure, since a single contig connection might completely change this number. I would rather look at NGx distribution plots (using Quast) to double check that the contiguity is consistent.

Mikhail
