### ISSUE TITLE
Final assembly bigger than genome size

### ISSUE THREAD

**Issue by matryoskina** [fenderglass/ABruijn#198]
Hi!
I work with a plant genome with 5 Gb genome size. Nanopore long reads used for the assembly. 
Already at the contigger stage the contigs.fasta file was 11 Gb, and after the polishing, I got the following statistics:
Total length:	11693620218
	Fragments:	61595
	Fragments N50:	311594
	Largest frg:	3347259
	Scaffolds:	69
	Mean coverage:	26

Do you have any idea why the total length is double the size of my genome? Even the N50 is quite low. I would send you the log file but is too big to be uploaded here.
Thanks in advance

**Comment by tolot27** [comment]
Ploidy?

**Comment by matryoskina** [comment]
It's diploid

**Comment by mikolmogorov** [comment]
Yes, as @tolot27 suggested it probably means that your genome is highly diploid and Flye assembled sequences from both haplotypes. This also explains lower N50 - more difficult to assemble. Since Flye does not currently produce pseudo-haplotypes (as does, for example, FALCON), the alternative haplotypes break contigs and further reduce the contiguity.

**Comment by shehongbing** [comment]
hi, 
I also confront the same question. my genome size is about 1G. And the final assemble is 1.3G. otherwise, the alignment with published genome shown than the genome I assembled by flye with more repetitive contains.

**Comment by mikolmogorov** [comment]
@shehongbing likely heterozygosity as well (Flye outputs divergent alternative haplotypes).

Closing the issue - feel free to reopen if you have follow-ups!
