### ISSUE TITLE
minimap2 crashes with SIGSEGV 11 on consensus stage

### ISSUE THREAD

**Issue by ptrebert** [fenderglass/ABruijn#213]
Hi,
I am using flye v2.6 on a PacBio Sequel2 CLR dataset; assembly is run with `--pacbio-raw` preset, `--asm-coverage 50` and a genome size of `3.1g`. The input data has ~75x coverage. In the log output, the following error appears:

```
-----------End assembly log------------
[2020-02-04 04:57:07] root: DEBUG: Disjointigs length: 3855703346, N50: 2066247
[2020-02-04 04:57:07] root: INFO: >>>STAGE: consensus
[2020-02-04 04:57:49] root: INFO: Running Minimap2
[2020-02-04 05:11:23] root: ERROR: Command '['flye-minimap2', '/PATH/10-consensus/chunks.fasta', 'SAMPLE.fastq.gz', '-x', 'map-pb', '-t', '72', '-a', '-p', '0.7', '-N', '10']' died with <Signals.SIGSEGV: 11>.
```

Is there a way of getting a more detailed log for the minimap step?

Best,
Peter

**Comment by mikolmogorov** [comment]
Hi,

Could you post the full Flye log? It could be related to #152 - which means that this is a rare bug in minimap2.

Something to double check is if you are not running out of disk space. If there is enough space, then try to resume the assembly with `--resume-from consensus` and check if minimap2 crashes again (in my experience, it does not crash every time on those problematic datasets).

Best,
Mikhail

**Comment by mikolmogorov** [comment]
Also, could you post the terminal output of the crash?

**Comment by ptrebert** [comment]
Hi,
the full (debug) log can be found in this gist:

gist.github.com/ptrebert/ca3d6561b09d87bba76c9849a1a864e0

The job was run on a cluster as part of a larger pipeline, so I don't have any terminal output, sorry.
Thanks for looking into this.

Best,
Peter

**Comment by mikolmogorov** [comment]
Hi Peter,

Thanks for sending the log - I didn't see anything suspicious there though. Please try my suggestions from the first message.

Mikhail

**Comment by ptrebert** [comment]
Ok, thanks. I'll restart the job (same thing happened also on another data set...), will take a few days until I know if it worked this time.

**Comment by ptrebert** [comment]
@fenderglass 
I have a second CLR sample with roughly the same specs that also ends up with a minimap segfault (same as the first). I also made a second attempt for the first sample with the same result, logs also look the same as far as I can tell. Running out of disk space cannot happen, unless flye "secretly" dumps data under local /tmp, then I would have to check with IT support how much local temp storage the compute nodes have.

**Comment by mikolmogorov** [comment]
@ptrebert thanks for testing. Since two different datasets are consistently crashing, the problem is probably different from #152. 

I suggest to try to build and run the latest code from the development branch `flye-devel` (not `flye`). It implements somewhat different pipeline for read alignment + stores minimap/samtools error output. I suggest to build the new version in a separate directory to make sure you start from a clean state (because of some changes in how binaries are packaged). 

If the `flye-devel` version also crashes, could you send the `10-consensus/minimap.stderr` file along with `flye.log`? Also, feel free to use `flye-devel` for your (presumably another) run from #188.

Best,
Mikhail

**Comment by ptrebert** [comment]
@fenderglass 
Ok, thanks a lot for your help and suggestions. I have to do these test runs on a different server, so it will probably take at least a week or so until I can give you some feedback.

**Comment by diana-moreno-santillan** [comment]
@fenderglass 
Hello, I am having the same problem. 
I have followed your suggestions also, I built flye-devel in a new directory but it keep crashing while running minimap2 during consensus step. 
It might be important to mention that this problem is only happening with PacBio raw data, I just ran Flye with nanopore raw data in the same server without any issues. 

Please find attached my flye.log and minimap.stderr output. 

Finally, I have read in this page that sequences starting with @ at the header might cause this problems My input sequences are fastq, is it okay if I substitute "@" for ">" in my fastq file? or should I just remove @ without adding any other symbol?

Thank you,

Diana Moreno 

[flye.log.log.gz](https://github.com/fenderglass/Flye/files/4216225/flye.log.log.gz)
[minimap.stderr.gz](https://github.com/fenderglass/Flye/files/4216226/minimap.stderr.gz)

**Comment by mikolmogorov** [comment]
@dianamosa 

Hi, looks like the same problem with minimap2, unfortunately. FastQ (not fasta) reads should start with "@", so the reads format should be fine.

Can you actually try to resume this run using `--nano-raw` mode instead of `--pacbio-raw` (and adding `--resume`). If it does go though, you would need to redo polishing using pacbio mode afterwards.

Mikhail

**Comment by ptrebert** [comment]
@fenderglass 
I just got the news that for one of the samples where 2.6/minimap crashed, flye 2.7b finished successfully. Several other sample have not yet been tested.

**Comment by ptrebert** [comment]
sorry, meant to just post a comment...

**Comment by mikolmogorov** [comment]
@ptrebert glad to hear! Please keep us updated about the remaining samples.

**Comment by ptrebert** [comment]
@fenderglass 
Interestingly, one of the samples that finished with 2.7b crashed with 2.7 (release); however, if the error message is the correct diagnosis, then I was just unlucky:

```
[omitted]
[2020-03-08 03:53:09] root: INFO: >>>STAGE: polishing
[2020-03-08 03:53:09] root: INFO: Polishing genome (1/1)
[2020-03-08 03:54:15] root: INFO: Running minimap2
[2020-03-08 16:19:56] root: ERROR: Error running minimap2, terminating. See the alignment error log  for details: /PATH/flye_test/HG00733_47rel_test/40-polishing/minimap.stderr
[2020-03-08 16:20:15] root: ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 /PATH/flye_test/HG00733_47rel_test/40-polishing/chunks_1.fasta HG00733_hgsvc_pbsq2-clr_1000.fastq.gz -x map-pb -t 48 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /PATH/flye_test/HG00733_47rel_test/40-polishing/chunks_1.fasta -u - | flye-samtools sort -T /PATH/flye_test/HG00733_47rel_test/40-polishing/sort_200308_035415 -O bam -@ 4 -l 1 -m 4G']' returned non-zero exit status 1.
[2020-03-08 16:20:15] root: ERROR: Pipeline aborted
[2020-03-09 14:58:29] root: INFO: Starting Flye 2.7-b1585
[2020-03-09 14:58:29] root: DEBUG: Cmd: /scratch/bioinf/users/pebert/software/conda/envs/biotools/bin/flye --resume-from contigger --asm-coverage 50 --pacbio-raw HG00733_hgsvc_pbsq2-clr_1000.fastq.gz -g 3088269832 -t 48 --debug --out-dir HG00733_47rel_test
[2020-03-09 14:58:29] root: DEBUG: Python version: 3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0]
[2020-03-09 14:58:29] root: INFO: Resuming previous run
[2020-03-09 14:58:29] root: INFO: >>>STAGE: contigger
[2020-03-09 14:58:29] root: INFO: Generating contigs
```

The minimap error log indicates a simple I/O failure:

```
[omitted]
[M::worker_pipeline::13390.154*34.73] mapped 16150 sequences
[M::worker_pipeline::13405.480*34.74] mapped 16349 sequences
[W::sam_read1] Parse error at line 16664363
[main_samview] truncated file.
[bam_sort_core] merging from 168 files and 4 in-memory blocks...
```

As you can see, I restarted from the contigger stage; I let you know if that happens again...

**Comment by mikolmogorov** [comment]
@ptrebert could be either an IO issue or the minimap2 crash that was reported previously: https://github.com/lh3/minimap2/issues/489

We are working on fixing the latter, but currently my best suggestion is to re-start the problematic stage (which you probably did already).

**Comment by ptrebert** [comment]
@fenderglass
Sorry, I was too slow updating this - yes, restarting from the respective stage worked, and the sample was assembled successfully! It was apparently just an I/O issue.
I think I close this for now, the other sample affected by this error was also assembled, albeit with worse stats. But we still have to check if that could also be an input problem.

Thanks again for your exceptional support!

**Comment by mikolmogorov** [comment]
@ptrebert glad to hear, thanks!
