### ISSUE TITLE
Impact of Trestle in NG50 in Final vs Draft assembly (related to #215, #51)

### ISSUE THREAD

**Issue by ppapasaikas** [fenderglass/ABruijn#220]
Dear Mikhail,
First off many thanks for the awesome software!

This is related to the question in #215 and possibly #51. I also see a dramatic drop in NG50 between Draft and Final assembly. In my case the drop is from 4Mbp to ~0.25Mbp. What is more I find the final NG50 rather on the low side as I have good coverage (~50x, chordate genome of size ~1Gbp) and high read N50 (18kbp ONT reads). 

Is  the trestle step (I run with --no-trestle as that step was hanging for more than 48h on 96 threads...) expected to have an impact on final NG50?
Or maybe this is typical behavior? 
Is there perhaps something else I am missing? Would e.g remnant adapters (I did not trim) have anything to do? 

Many thanks!

**Comment by mikolmogorov** [comment]
Hi,

Trestle usually has little impact on NG50, as it resolves only a few extra repeats.  I can comment more on your case, if you could send a log file and describe the dataset in details. 

Because Trestle is taking a lot of time, it is possible that the genome is highly diploid - they are not well supported by Flye, currently.

Mikhail

**Comment by ppapasaikas** [comment]
Dear Mikhail,
Thank you for you reply. I can confirm that my genome is indeed diploid but I am not sure it qualifies as "highly diploid"  (allele  SNP is estimated at ~0.8%).  
Please find attach the log file from a recent Flye run. 

Currently I am trying runs with different `-m` parameters. Auto choice was 5kb. I've seen that increasing this value to 8-10kb gives somewhat better results. Lower values are definitely detrimental. I am not sure if a different --asm-coverage choice -now set at 30- would help.

Thanks again for taking the time to have a look at this.
[flye_M.log.gz](https://github.com/fenderglass/Flye/files/4224143/flye_M.log.gz)

**Comment by mikolmogorov** [comment]
@ppapasaikas Ok, I didn't see anything suspicious in the log. I think in your case heterozygosity is the challenge: there are ~2600 bubbles on the graph (caused by alternative haplotypes), in comparison to 200-600 for a typical human assembly (with 3x longer genome). 

It definitely makes sense to try higher min overlap (7k+). I am also planning to release a new version 2.7 within a week or two, which might improve things a little. 

Otherwise, diploid genes are a challenge in general, Flye currently does not handle them well. I'm marking the issue closed, but feel free to follow up if you have more questions!
