### ISSUE TITLE
Flye v2.7 produces much smaller metagenomics assembly

### ISSUE THREAD

**Issue by hoelzer** [fenderglass/ABruijn#231]
I observed a much smaller overall assembly size using the same Flye command between version 2.5 and 2.7. 

__Flye v2.7__
ASSEMBLY SIZE: 68M
LOG: [2020-03-05_flye_v2.7.log](https://github.com/fenderglass/Flye/files/4295589/2020-03-05_flye_v2.7.log)

__Flye v2.5__
ASSEMBLY SIZE: 399M
LOG: [2020-03-05_flye_v2.5.log](https://github.com/fenderglass/Flye/files/4295593/2020-03-05_flye_v2.5.log)

__Command used in both cases__
```bash
flye --nano-corr $ONT -o out --plasmids --meta --genome-size 422.33m
```

The genome size was estimated based on unique k-mer counting based on the input reads. So the assembly size of v2.5 actually fits quite well with the estimation. 

Used reads are also available here: 
```
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR366/002/ERR3661022/ERR3661022_1.fastq.gz
```

**Comment by mikolmogorov** [comment]
Ok, thanks for sending the data. Seems like the issue is that you were using `--nano-corr` option that is intended for error-corrected reads. Based on the logs, it seems that you have raw ONT reads, so you need to use `--nano-raw` instead. This explains the difference in size, since the version 2.7 is more strict wrt to read alignment identity thresholds. I would suggest to re-run the entire pipeline using `--nano-raw`.

**Comment by hoelzer** [comment]
Ok, thanks for looking into this. I will test it with the raw option and report back.

So the ``nano-corr`` option should be used when I somehow polish my long reads (e. g. with illumina) before the assembly?

**Comment by hoelzer** [comment]
I calculated the assembly again using the ``--nano-raw`` option and you were right, now I have an assembly file size of 338Mb.

__Summary__:

Flye v2.5 w/ ``--nano-corr``
ASSEMBLY SIZE: 399M

Flye v2.7 w/ ``--nano-corr``
ASSEMBLY SIZE: 68M

Flye v2.7 w/ ``--nano-raw``
ASSEMBLY SIZE: 338M

So I guess v2.7 might be still a little bit more restrictive when it comes to low coverage regions in the graph? Anyway, going with ``--nano-raw`` seems to solve the issue for me. Thanks!

**Comment by mikolmogorov** [comment]
Ok, glad that it worked now. I would not draw any comparisons against the `--nano-corr` assemblies, since running Flye with in incorrect mode breaks many assumptions that the algorithms are making.

Yes, `--nano-corr` option is for error-corrected reads, for example using Illumina or self-correction with Canu.
