### ISSUE TITLE
minimum contig size for subassembly?

### ISSUE THREAD

**Issue by bresyd** [fenderglass/ABruijn#260]
Hi Mikhail,

I have a flye assembly of a pacbio metagenome and I have a megahit assembly from an illumina metagenome (both from the same DNA preparation). I would now like to combine the two assemblies and I thought I could use the flye subassembly option for this. Currently the megahit assembly has a minimum contig length of 200nt (and most contigs are between 200-1000nt) which appears relatively short as input for a long read assembler like flye. I was wondering if there is a minimum contig size that I should use as input for --subassembly?  I could e.g. remove contigs <1 or 2 kb from the megahit assembly prior to flye --subassembly if there is any benefit.

Thanks a lot for your help,

**Comment by mikolmogorov** [comment]
Hi,

Flye will not use contigs shorter than minimum overlap length (1 kb in subassmbly mode) - so there is no need for additional filtering. I am not sure what is the best recipe for merging long-read and Illumina metagenomes though. Before merging, I would suggest to polish PacBio contigs with Illumina using Pilon/Racon, since you might have a lot of contigs with low coverage (and poor consensus) in metagenomes.

Mikhail
