### ISSUE TITLE
Flye draft assembly is much more 'correct' than final assembly?

### ISSUE THREAD

**Issue by chocotwig** [fenderglass/ABruijn#266]
Hi,
I ran Quast on a Nanopore long read assembly set (used wtdbg2 +/- LRScaf for scaffolding) and also used Flye for the same data. After assembly QC with Quast, I am seeing that the final assembly from Flye is far, far more misassembled than the draft-00 assembly (and also wtdbg2 assemblies).
Why do you think such dramatic misassembly is seen? Am I missing something? The reference genome is characterised. I am wondering if it could do with the way Quast works.

Thanks! 

Attached: misassemblies_report.txt from Quast

![image](https://user-images.githubusercontent.com/52871301/82583607-dfd44000-9bb0-11ea-8a68-6b5ea3455ba5.png)

Also: genome_info.txt from Quast (while the flye assembly is ~4x more complete than the wtdbg2 assembly, it contains a disproportionately large number of misassemblies).
![image](https://user-images.githubusercontent.com/52871301/82609229-b54aad00-9bd9-11ea-8675-e3585b1cd4f0.png)

**Comment by mikolmogorov** [comment]
Hi,

Simply counting the number of misassemblies could be misleading. In your case, looks like the reference is quite distant from the assembled genome, based on the reference coverage ("genome fraction" column). Usually you would expect it to be close to 100%. 

Since the final flye assembly has much higher coverage, it is not surprising that the number of misassemblies is also higher (more regions are available for misassembly testing). Because the reference is apparently distant, I expect that most of the misassemblies would reflect structural variations between the genomes, rather than assembly errors.

Best,
Mikhail

**Comment by chocotwig** [comment]
Thanks a lot for your response. The reference is pretty close (same species). Although the coverage is patchy and reads are not of enough depth, which may explain partial assembly. It is a bit strange that genome fraction for the flye final assembly is so, so much higher than the draft. Do you find that normal? Thanks!

**Comment by mikolmogorov** [comment]
@chocotwig completely normal - draft assembly has much higher base error rate, thus less sequence was aligned to the reference.
