### ISSUE TITLE
can't start new thread

### ISSUE THREAD

**Issue by jdmontenegro** [fenderglass/ABruijn#29]
Hello everyone,
I'm trying to get flye to run using similar parameters as I did with Abruijn. I'm using a Centos 7.0 with 1.5Tb of RAM and 64 cores (128 threads). With the following command:
`flye --pacbio-raw ${reads} -g 3g -o ${OD} -t 127 -i 3`
The program executes for 15 hours and then it fails with a series of error, the firs of which is the following:
```
[2018-01-08 10:03:43] INFO: Running Flye 2.3-release
[2018-01-08 10:03:43] INFO: Assembling reads
[2018-01-08 10:03:43] INFO: Reading sequences
[2018-01-08 10:20:58] INFO: Generating solid k-mer index
[2018-01-08 10:25:51] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-01-08 10:29:21] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-01-08 10:51:10] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-01-08 11:46:11] INFO: Extending reads
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-01-08 22:26:16] INFO: Assembled 226679 draft contigs
[2018-01-08 22:30:40] INFO: Generating contig sequences
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2018-01-08 23:28:59] INFO: Running Minimap2
[2018-01-09 01:13:13] INFO: Computing consensus
Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 184, in serve_forever
    t.start()
  File "/usr/lib64/python2.7/threading.py", line 747, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
(...)
```
and then just continues complaining about all the threads that failed, then missing or empty files and then it finishes. I know that Abruijn was able to use all the 128 threads available in the node, is there a limit to the number of threads that Flye can start?, Would it be better to drop the number to 64 or something like that?

Best regards,

**Comment by mikolmogorov** [comment]
Hi, 

There was a multithreading issue in the consensus caller (see #28). The new version should work fine - sorry about that. You can continue the current assembly by using '--resume'.

**Comment by jdmontenegro** [comment]
Hi, 

The new version finished correctly this time so the fix worked.
As an overall comment, even though the assembly metrics look good, the abruijn assembly stats looked much better than the current Flye assembly:
Abruijn:              N50-> 429.9 Kbp, longest->2.3 Mbp, AvgContig -> 187.3 Kbp
Flye(scaffolds):   N50-> 69.8 kbp,   longest-> 500 Kbp, AvgContig -> 48.1 Kbp

So overall, it is a 4 fould reduction in contiguity in the assembly. Comparison of the Abruijn assembly to hg19 showed no obvious missassemblies (using mummer 4.0). Is there any particular parameter that would need to be used to improve or at least mimic the results obtained with the original Abruijn?

Best regards,

**Comment by mikolmogorov** [comment]
Hi,

This seems strange, the main algorithms should not have changed much actually. Is it possible for you to share the log files from both runs (you can send them to fenderglass@gmail.com)? It would be much easier to tell what went wrong.

**Comment by mikolmogorov** [comment]
Hi,

I think it must be that two runs have different min-overlap parameter. As I understand you used 2000 in your original run, and the most recent one was done with 5000? If so, I would recommend to re-run with 3000 or 2000. Sorry, this parameter for older PacBio chemistry might be tricky..

You should be able to tell if your new run is roughly similar to the old one by comparing the number of assembled draft contigs (in the log). To save time, you can actually re-use the old assembly and restart it from the repeat analysis stage. Because the output format has changed, you will need to do some renaming though: create a folder called "1-consensus" and copy the "polished_0.fasta" file into it with a new name: "consensus.fasta". Then you should be able to do "--resume-from repeat". In case you want to resume the run, make sure that min-overlap parameter is consistent with the previous assembly stages.

Let me know if this helps, I think we should make this parameter automatically selected in the future releases..

**Comment by mikolmogorov** [comment]
Seems that the problem was resolved some time ago, closing this one...
