### ISSUE TITLE
Issues with final assembly contig numbering and final assembly graph

### ISSUE THREAD

**Issue by jade-davies** [fenderglass/ABruijn#295]
Hello,

I ran flye 2.7.1 successfully on my nanopore reads, but I am a bit confused by the final results. Looking at the assembly file, it looks like 6 contigs were produced, but the numbering is not expected - contig_1, contig_10, contig_3, contig_5, contig_6, contig_9.

When visualising the assembly graph, it looks like there are 10 contigs (please see attached image).

Please let me know your thoughts about this.

Thanks,
Jade

![unknown_species_flye_assembly_graph](https://user-images.githubusercontent.com/63346289/90008146-d16b6100-dc93-11ea-9d41-82108af1dbaa.png)

**Comment by mikolmogorov** [comment]
Hi Jade,

There are two reasons for having fewer contigs than graph edges. First, some contigs might consist of multiple edges - this information is show in the `assembly_info.txt`. Second, Flye filters out contigs that have very low read coverage after the final polishing iteration. The final coverage might also change as compared to the graph output stage, since some reads may be reassigned.

Hope this helps,
Mikhail
