### ISSUE TITLE
Flye did not assemble short circular genome (e.g. chloroplast)

### ISSUE THREAD

**Issue by Silverfoxcome** [fenderglass/ABruijn#301]
Good day!
I wanted to comment on something that happened a few days ago. I know that flye 2.8 works really well assembling large genomes. But something strange happened while I was trying to assemble a little chloroplast genome (that usually ranges between 139-150k) with nanopore reads downloaded from SRA (SRX5632308). I made sure that the average coverage (100x) and depth were good enough, besides, I was working with a set of reads that were equal or larger than 20k bp. Then, I ran flye (v2.8) with the following command:

`$ flye --nano-raw cp.reads.fq -o ../assembly/ --threads 10 -i 7`

But no matter which parameters I used (with or without specifying --genome-size 150k), flye 2.8 always gave me the same error message:

> [2020-09-07 08:25:27] INFO: Assembled 0 disjointigs
> [2020-09-07 08:25:27] INFO: Generating sequence
> [2020-09-07 08:25:27] ERROR: No disjointigs were assembled - please check if the read type and genome size parameters are correct
> [2020-09-07 08:25:27] ERROR: Pipeline aborted

I tried different sets of reads with similar features but the result was always the same. I was thinking that perhaps the data was the problem and was about to look up for a different accession when I thought of trying flye 2.7, the version I have used more. I gave this version the same set of reads and the same parameters and it worked, it assembled the cp genome. I gave flye 2.7 another set of reads that I’ve also tried before with flye 2.8 (without success) and it worked again, with similar results!

I finished assembling my cp genomes using the 2.7 version but I post this here just in case someone else is experiencing something similar and because I want to know what could have caused this behavior in the 2.8 version.

Thanks a lot in advance!

**Comment by mikolmogorov** [comment]
Hi,

Hard to tell what went wrong without looking at the data here. Do you mind sending the log files from both 2.7 and 2.8 runs? The version 2.8 is using a different approach for k-mer selection (which was enabled in --meta mode in the previous versions). I think this might have affected the assemebly somehow. In general, Flye is not tuned for assembling short sequences (e.g. 10-10 kbp or so).

Also, if you could send me the set of chloroplast reads you were using as input - it will help to debug the problem faster.

Mikhail

**Comment by Silverfoxcome** [comment]
Hi!! Thank you for your answer! 

Here is one of the sets of reads that didn't work in flye 2.8 but worked in flye 2.7: 
https://www.dropbox.com/s/hazek4e9kg5zc3y/cp.reads.fq?dl=0

[assembly.10.flye2.7.log](https://github.com/fenderglass/Flye/files/5259039/assembly.10.flye2.7.log)
[assembly.10.flye2.8.log](https://github.com/fenderglass/Flye/files/5259040/assembly.10.flye2.8.log)

Thanks a lot for your help in advance :)

**Comment by mikolmogorov** [comment]
@Silverfoxcome thanks for sending the data!

Indeed, I was able to assemble the chloroplast genome using Flye 2.7, but not 2.8. The issue is somewhat complicated - Flye currently is not designed for assembling short sequences (that is, comparable or shorter than input read length). In this case, you chloroplast genome is somewhat "borderline", so the version 2.7 did consider it as long enough, but due to some changes the version 2.8 filtered it out for being too short.

A  counter-intuitive solution for assembling short sequences is to run Flye on the whole set of reads, without any length or sequence-based filtering (and then extract the sequence of interest). There is also some experimental code in the `short_disj` branch that is based on version 2.8, but doing much better job in reconstructing short sequences. We are planning to incorporate it into the main code base in the next release.
