### ISSUE TITLE
Question regarding repeat assembly

### ISSUE THREAD

**Issue by sjackman** [fenderglass/ABruijn#31]
Hi, Mikhail. I've read your preprint and found the correspondence of repeat graph construction problem and the assembly problem intriguing! I was left confused about one particular aspect: when assembling a linear genome `ARBRC` with a two-copy repeat `R`, my understanding of the algorithm goes like this:

1. select a read at random from `UnprocessedReads`, selecting a read from `A`
2. follow a random walk from that read which assembles the contig `ARC`
3. map the reads to that contig and remove those reads from `UnprocessedReads`
4. `UnprocessedReads` now contains only reads from `B`
5. select a read at random from `UnprocessedReads`, selecting a read from `B`
6. follow a random walk from that read which assemble the contig `B`, since `UnprocessedReads` contains no reads from `ARC`
7. map the reads to that contig and remove those reads from `UnprocessedReads`
8. `UnprocessedReads` now contains no reads. Stop assembling contigs, and identify repeats.

The assembled contigs are `ARC` and `B`. How is Flye able to identify `R` as a repeat? Thanks for the clarification!

Note: In Acknowledgments, `Bahar Beshaz` should be `Bahar Behsaz`. We worked together at the BC Cancer Genome Sciences Centre in Vancouver!

**Comment by mikolmogorov** [comment]
Hi,

At the step 4 here, ```UnprocessedReads``` will contain reads fully contained in ```B``` (as you said), but it will also contain reads that start in ```R``` and end in ```B```, and likewise reads that start in ```B``` and end in ```R``` (since these reads are not contained in full in the ```ARC``` path). So, during the step 6, you will assemble ```B```, but the contig will also contain flanking sequence from ```R```. This will allow to connect ```B``` and ```ARC``` parts in the graph (and reveal the repeat).

It's nice to meet a friend of Bahar! Thanks for letting us know, we will fix this as soon as possible.

**Comment by sjackman** [comment]
Thanks for the explanation, Mikhail. I appreciate it. Say hi to Bahar from me!
