### ISSUE TITLE
using CCS+ONT data

### ISSUE THREAD

**Issue by longzhangnation** [fenderglass/ABruijn#312]
Hi,
  I have 40X depth nanopore data and 15X depth CCS data , can I mix the two data for genome assembly ?  Or should I correct the nanopore data and use the corrected nanopore plus CCS data for genome assebly ?  I noticed that in the FAQ ,flye will now support genome size large than 10G . So I have one genome for 6G , can I use it for assemblying ? Thank you .

**Comment by jelber2** [comment]
`Wengan v. 0.2` (https://github.com/adigenova/wengan) has an option for combining PacBio HiFi and ONT reads. Haven't tried it though. See (https://github.com/adigenova/wengan/issues/23#issuecomment-674888991)

**Comment by mikolmogorov** [comment]
@longzhangnation currently you can not mix ONT and CCS data with Flye directly, since the error rates are so different. 

As you suggested, you can try to error-correct ONT, and then use it together with CCS using `--nano-corr` option. But this will not take full advantage of CCS reads. Onether way could be to perform two separate assemblies, and then merge them using `--subassemblies` mode. Wengan (as suggested above) could be a good solution.

Yes, you should be able to assemble 6Gb genome.

Mikhail

**Comment by longzhangnation** [comment]
Ok ， I have read the Wengan manual and noticed that it is not suitable for genome size > 4G . So I just have to use nanopore for assembling . Digress from the topic at hand, I have used flye  about half a year ago, and at that time it coud only assemble those genome whose size below 5G , so when the software could assemble genome below 10G？ @jelber2 ,thanks for your advice.

**Comment by mikolmogorov** [comment]
@longzhangnation we have not tested Flye on 10Gb genomes, but theoretically it should work, provided that you have a machine with 1Tb+ RAM.

**Comment by fjruizruano** [comment]
Hi,

Is still not possible to combine PacBio HiFi with ONT in a Flye assembly?

Thanks in advance,
Francisco.

**Comment by mikolmogorov** [comment]
@fjruizruano still not possible. This turns out to be a pretty difficult problem to solve.

**Comment by fjruizruano** [comment]
Thanks for letting me know @fenderglass! I can imagine that it's not that straight forward to make it work. At the moment, I am trying to use GraphUnzip to incorporate ONT evidence to the HiFi assembly graph. Let's see how it works.
