### ISSUE TITLE
Are overlapping ends removed in circularized contigs?

### ISSUE THREAD

**Issue by frihaka** [fenderglass/ABruijn#315]
Hi Fenderglass,

thanks for providing us with Flye, excellent tool for assemblying smoothly bacterial genomes.

I have a question: does it remove the **overlapping ends** of **circularized** contigs?
I am asking because the ends are often different between circularized assemblies output by Flye and by SMRTLink8.

Thanks,

ps: apologies if this was covered already in a previous post, I could find about raw reads (#100) and circularized final assembly (#199) trimming but not exactly my question

**Comment by mikolmogorov** [comment]
Hi,

Yes, Flye does remove overlapping ends on circular contigs. Some people have reported that Flye might occasionally delete a small number of bases (~10 bp) at the circularization point. Also, Flye does not "rotate" genome so that origin of replication is in the beginning - you can use Circlator  for that task.

Mikhail
