### ISSUE TITLE
Interrupted run, KeyError: '*'?

### ISSUE THREAD

**Issue by KyleTDavid** [fenderglass/ABruijn#316]
Hello,

I just ran an assembly and while the log file doesn't seem to indicate anything went wrong I received a KeyError: '*' in stdout and the run was apparently interrupted.

run command:
> flye --pacbio-hifi ~/brittlestar_genomes/Aagassizii.fastq  --o Aagassizii --threads 50

contents of output directory:
> flye.log  params.json
> 
> 00-assembly:
> draft_assembly.fasta
> 
> 10-consensus:
> chunks.fasta  chunks.fasta.fai  consensus.fasta  minimap.bam
> 
> 20-repeat:

I've also attached stdout for the run and the last few lines of the log file, let me know if you have any ideas or need anything else.

-Kyle

[logtail.txt](https://github.com/fenderglass/Flye/files/5483423/logtail.txt)
[stdout.txt](https://github.com/fenderglass/Flye/files/5483425/stdout.txt)

**Comment by mikolmogorov** [comment]
Hi @KyleTDavid 

Are you using conda package, or you compiled/installed Flye manually? This error might be a result of multiple Flye versions installed at the same time, resulting in a conflict. If you used a manual installation before, I'd suggest to try again with a bioconda package installed into a clean environment. Feel free to use `--resume-from consensus` to restart from the completed assmebly stages.

If the problem is not solved, could you send the full `flye.log`?

Mikhail

**Comment by KyleTDavid** [comment]
@fenderglass,

I was using conda, I reinstalled into a fresh conda environment and resumed the job but ran into the same issue, full log attached.
[flye.log.gz](https://github.com/fenderglass/Flye/files/5540208/flye.log.gz)

-Kyle

**Comment by mikolmogorov** [comment]
@KyleTDavid 

Thanks for sending the log files. I noticed that you already have done another run on the same data that progressed to the repeat stage (and passed the consensus stage). You can reuse that results and restart your run using `--resume-from repeat`, without the need of repeating the consensus stage.

In case you are interested in helping me to debug the error at the consensus stage in the most recent run - you can get the latest code from the `flye` branch and do `--resume-from consensus` again. This probably will not fix the error, but it should provide a much more detailed report which will help me to identify where the error is happening.

Mikhail
