### ISSUE TITLE
Cannot install Flye

### ISSUE THREAD

**Issue by ivywtl** [fenderglass/ABruijn#322]
Hi there - i'm a newbie to python and i kept running into this error while installing Flye - what might be the problem? thank you.

running install
running build
running build_py
process_begin: CreateProcess(NULL, dirname C:/Users/tlwong/Flye/makefile, ...) failed.
make -C /lib/minimap2 -j 4
make: *** /lib/minimap2: No such file or directory.  Stop.
make: *** [/bin/flye-minimap2] Error 2
Traceback (most recent call last):
  File "setup.py", line 38, in run
    subprocess.check_call(["make"])
  File "C:\Users\tlwong\Miniconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    setup(name='flye',
  File "C:\Users\tlwong\Miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\tlwong\Miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\tlwong\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\tlwong\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "C:\Users\tlwong\Miniconda3\lib\site-packages\setuptools\command\install.py", line 65, in run
    orig.install.run(self)
  File "C:\Users\tlwong\Miniconda3\lib\distutils\command\install.py", line 545, in run
    self.run_command('build')
  File "C:\Users\tlwong\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\tlwong\Miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 argument, got 2

**Comment by mikolmogorov** [comment]
Hi @ivywtl,

Looks like you are on Windows - unfortunately Flye only supports Linux and MacOS.

**Comment by katievigil** [comment]
I have a problem installing Flye 2.9.  I was able to install flye 2.8 using "conda install -c bioconda flye" , but I need 2.9 version because I do not know my genome size. y
(base) mumu@DESKTOP-92GK8RD:~$ conda install -c bioconda flye
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/mumu/anaconda3

  added / updated specs:
    - flye


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.10.3               |   py37h06a4308_0         2.9 MB
    flye-2.8.1                 |   py37h1c8e9b9_0        26.7 MB  bioconda
    ------------------------------------------------------------
                                           Total:        29.5 MB

The following NEW packages will be INSTALLED:

  flye               bioconda/linux-64::flye-2.8.1-py37h1c8e9b9_0

The following packages will be UPDATED:

  conda                                        4.8.2-py37_0 --> 4.10.3-py37h06a4308_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
flye-2.8.1           | 26.7 MB   | ########################################################################## | 100%
conda-4.10.3         | 2.9 MB    | ########################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
