### ISSUE TITLE
Flye outputs a scaffold which maps to two different chromosomes.

### ISSUE THREAD

**Issue by MehmetGoktay** [fenderglass/ABruijn#339]
Hi,

I have made two assemblies with the same nanopore reads one with flye and one with minimap2 + miniasm.

Flye produced a weird scaffold, when I map it to the reference genome, half of the scaffold maps to one chromosome, and the other half maps to another chromosome.

But when I use minimap2+miniasm this does not occur.

Does anyone have any idea what would cause this weird scaffold? (setting genome size shorter than expected?) or any other thing that would cause this?

![ss1](https://user-images.githubusercontent.com/8544565/105417448-f1884e80-5c3b-11eb-8f14-4a4183001fee.png)

Any help is highly appreciated!

Best,
Mehmet

**Comment by mikolmogorov** [comment]
Likely an error in Flye assembly. Although rare, misassmeblies happen sometimes because of incorrectly resolved repeats. You can check if the file `40-polishing/filtered_contigs.fasta` contains the error - these are contigs before the scaffolding stage.

If that is a random error (e.g. not systematic) - than another Flye run will likely fix it. Try manually setting `-m` (minimum overlap) parmeter to either + or - 1k as compared to the automatically selected value.

**Comment by MehmetGoktay** [comment]
Based on my several assembly attempts I found out that, when I set the expected genome size, for some samples, I always get this awkward misassembly. So it looks like it is not random. 
Surprisingly when I don't set the expected genome size then I got normal assembly. It looks like sometimes setting genome size (or setting wrong genome size) forces systematic misassembly.

**Comment by mikolmogorov** [comment]
@MehmetGoktay starting Flye 2.8 you no longer need to input assembly size, and the parameter does not have any effect on the assembly, except in conjunction with `--asm-coverage` option.

**Comment by MehmetGoktay** [comment]
Okay. Thank you very much for your help!
