### ISSUE TITLE
Create intermedian files for recovery during kmer or extension of the reads?

### ISSUE THREAD

**Issue by Imoteph** [fenderglass/ABruijn#36]
Hi,

Flye was nearly killing one of our nodes through RAM and SWAP uptaking. It was in the first phase and from observation only the first folder structure and the logs where produced. Is it possible to dump some files during this stage? I assume that if no further files are generated, it will start from scratch during a crash?

**Comment by mikolmogorov** [comment]
Hi,

Flye does have multiple running stages, and they could be resumed if something went wrong with the machine (probably the stages might not be as granular as we would like). The problem here is that the first contig extension step could be a memory bottleneck for large datasets (genome size 1Gb+), and since the read index should be kept in memory, the generation of intermediate files won't really help. The maximum dataset we have assembled so far was human genome at 35x coverage, which took about 700Gb of RAM at peak. We are exploring the possibilities of reducing RAM usage, but currently accuracy and completeness of the assemblies are the priority.

**Comment by Imoteph** [comment]
Thank you very much for your answer! And looking forward to the new developments!
