### ISSUE TITLE
Variation of RAM usage with sequencing depth

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [fenderglass/ABruijn#362]
Hello,

Thank you for this assembler. 

I have run some tests on RAM usage (with v2.5, as these tests were already some time ago). I used subsets of PacBio or Nanopore reads from big datasets to test the impact of sequencing depth. I found that the maximum RAM usage was not linear with higher sequencing depths for Nanopore reads. Do you have an idea why?

**Comment by mikolmogorov** [comment]
@nadegeguiglielmoni That's completely normal, in addition to memory for read indexing, Flye has other temporary memory buffers, which may consume substantial amounts of RAM on some datasets. I also recommend to use the latest release, since it improves a lot over 2.5 in terms of RAM usage. 

Mikhail
