### ISSUE TITLE
Override min overlap restriction

### ISSUE THREAD

**Issue by Adamtaranto** [fenderglass/ABruijn#37]
Hi there, 

I'm trying to assemble an older PacBio dataset in which many of the reads are ~1000bp. Flye does not allow the min overlap threshold to be set any lower than 1000bp - I think that this might be why my final assembly has many contigs of roughly this size.

Is there a good reason not to run flye with a lower limit? and if not, how can disable the error message?

Cheers,
Adam

**Comment by mikolmogorov** [comment]
Hi,

What is the mean read length of the dataset? Does the resulting assembly has poor N50 (lower than expected)?

Flye computes approximate ovelaps between the noisy reads, this is why we require the mean overlap length to be relatively long (otherwise there will be many false positives). If you can tell me more details about the dataset, I may be able to help with choosing better parameters.

**Comment by lautimothy** [comment]
Hi Mikhail,

I am having a similar problem: input reads too short for the min-overlap parameter to be set at 1000.   The expected genome size is ~1Gb and the resultant assembly was 531Mb, with N50 at 34317.   In comparison, we did a short read assembly for the same genome with Illumina reads at 100X coverage, the assembly size was 1Gb and scaffold N50 93506.

To be fair, our input nanopore reads aren't the best, short in length and low in coverage.  Probably shouldn't expect much from them in the first place, and I understand you would rather flye output correct rather than long contigs.    Just wondering if there's anything more we can do, e.g. tweak the min-overlap to be lower than 1000 or change some other parameters to improve the assembly.

Read metrics:
mean read len = 1250.736
median read len = 787
max read len = 76743
min read len = 100
coverage = 11178973957  (10X)
read count = 8937914
N50 / N90 = 1877 / 557

Thanks,
Tim

**Comment by mikolmogorov** [comment]
Hi Tim,

I don't see much you can do in this case to improve the assembly - it's just very short reads. I would try hybrid assembly instead.

Best,
Mikhail
