### ISSUE TITLE
find path in graph based on close relative

### ISSUE THREAD

**Issue by jdmontenegro** [fenderglass/ABruijn#381]
Hi @fenderglass 
I have been a regular user of Flye for a few years now. I wanted to know your opinion on using a closely relative chromosome assembly genome to find a chromosome paths in the assembly graph produced by Flye. 
I have considered doing traditional scaffolding using the assembly.fasta, but I get a feeling that some of the repeats that have not been solved in the assembly could be solved by using the close relative genome and thus, we could deduce a longer likely path in the assembly graph to produce longer contigs. Do you think this would make sense? I am looking for approaches to the chromosomes to a genome graph, but the tools are limited and very memory intensive. 
Your view/sugestions would be more than welcome.

Regards,

Juan D. Montenegro

**Comment by mikolmogorov** [comment]
Hi Juan,

I agree, using assembly graph rather than contigs for reference-based assembly should theoretically produce better results with fewer gaps. I am not aware of any tools that can currently do that automatically. There are tools that can align long reads to gfa (e.g. https://github.com/maickrau/GraphAligner), and perhaps you can use those to align reference as well. Then it should be possible to convert graph alignment paths to contigs. 

Since it is not directly related to Flye functionality, I'm marking thread as resolved, but feel free to follow up!

Best,
Mikhail
