### ISSUE TITLE
[Question] help with understanding .gfa

### ISSUE THREAD

**Issue by RxLoutre** [fenderglass/ABruijn#389]
I love .gfa, but sometimes I have trouble to understand them.

I have used Flye with pacBio reads with defaults options to make a first shot at assemble a linear bacterial genome. The genome probably contains some plasmids or some phages sequences. Flye gave me the following .gfa :

GFA Of bacterial assembly with flye

![Screenshot 2021-05-25 at 15 39 47](https://user-images.githubusercontent.com/13352219/119616898-74473300-be01-11eb-8d16-6ed60ab4c759.png)

The green, yellow and red edges have been merged into one scaffold of around 9 Mb (as expected). And the little blue edge is his own contig of 42 Kb.

In his assembly_infot.txt file, Flye report that the big scaffold is indeed non linear, and that the tiny one is circular :

```
#seq_name   length  cov.    circ.   repeat  mult.   alt_group   graph_path
scaffold_2  8926751 84  N   N   1   *   *,1,2,4,??,4,-3,-1,*
contig_4    42310   940 N   Y   12  *   4
```

I have a few questions that puzzles me about this graph :

- Why does the .gfa connect all the edges into a circle if flye report that only one piece is circular not the other ?

- The yellow edge is connected by the same end to both green and red... And if the mean coverage of the green and red is 70X, it is only 17X for the yellow edge. What could it mean ? I am very puzzled by the fact it is connected by the same end. Could it be Flye trying to circularize it ? Or a sort of SV ? I think the DNA provided comes from a single colony so I don't see how that could be a SV.

- The blue edge has connection to itself, I imagine it is because of repetitions. But in the graph, this repetition is somehow connected to the others edges. So why was it split in the .fasta file in the end ?

    
    Thank you for your help 😃

**Comment by mikolmogorov** [comment]
Hi,

Thank you for the interesting example :)

1. Flye did not report any contigs as circular - "Y" in the contig_4 raw refers to the contig being repetitive.

2. That graph would certainly indicate some kind of assembly issue for a regular circular chromosome, but since you know that the genome is linear, it actually makes sense. I'd suggest that your chromosome has long(ish) inverted terminal repeat, that corresponds to the yellow edge. So the chromosome starts in yellow, goes around the loop and comes back into the yellow edge, but from a different direction (thus, inverted repeat). Not sure why the coverage is lower, but that could reflect read sampling bias towards the end of chromosome.

3. The self-connection for the blue edge indicates a tandem repeat. Flye did not find any reads that fully span the repetitive part, and it remained unresolved. Based on the coverage, you can estimate that it has ~10 copies of the blue edge (so, potentially a very long ~400kb repeat).

Hope this helps,
Mikhail

**Comment by RxLoutre** [comment]
Hi Mikhail ! 

Thank you for your answer :) That actually helps a lot. So you have no hypothesis of why the blue edge was connected to green and red ? Would it mean that part of the inverted repeat overlaps the beginning/end of the linear chromosome ? 

I have tried to isolate the sequence of each edge (using bandage) and map it to the assembly, I then visualized it in IGV, , I was curious of how flye solved the yellow connection. It seems that yellow bring an uniq sequence to the scaffold2 for the first 5Kb, and then it overlap the green edge for about 500 more KB, and then scaffold2 is basically green edge. There is then a "hole" where no edge map to the assembly, for like 20-30 Kb, and then there is the red edge. So I have trouble to understand what happened.

Here is a simplified draw of what I observed in IGV (grey is scaffold2): 

![Screenshot 2021-05-27 at 12 11 08](https://user-images.githubusercontent.com/13352219/119809230-2d326e00-bee5-11eb-8b54-132ad63416ad.png)


The blue edge align entirely to the little contig4, but then I still don't understand why the inverted repeats matched to some portions of green and red.. Could this explain the hole between red and green that I see when aligning the edges against the assembly ?

**Comment by mikolmogorov** [comment]
Yellow and blue edges are different repeats and are unrelated. The blue edges is connected because it is a part of the chromosome. But since the number of copies is unknown, it is represented as a loop.

Normally graph edges should not overlap - so I am not sure why it is happening. It is difficult to say without looking into actual alignments / assembly.

**Comment by RxLoutre** [comment]
Yeah, I don't know if I should trust the alignment. Big repeats make it often difficult  !

Looking closely at assembly_info.txt again, I see I have missed an important information I was looking for which is the graph path for the making of the contigs / scaffolds. I have made a drawing of how I interpret the output : 

![Screenshot 2021-05-28 at 12 28 18](https://user-images.githubusercontent.com/13352219/119971279-0b9eb880-bfb1-11eb-9181-2d185da5a42b.png)

Is my drawing correct ? It does seems to support, as you mentioned, that the big repeat is a part of the chromosome and caused the gap in the assembly. I come back on something you said but now I doubt I understood it properly : 

_"Based on the coverage, you can estimate that it has ~10 copies of the blue edge (so, potentially a very long ~400kb repeat)."_

So, only the .gfa gives an indication of the number of copies (via the coverage). The blue node is 42 Kb, and it says it has 1200 X. In the .fasta, the blue node becomes contig 4, of 42 Kb as well. But in reality, it might be bigger than 42 Kb because of the high coverage, is that correct ? Also, I don't understand how you estimated it to 10 copies with the 1200 X coverage (might be a dumb question).

Thank you again for your help ! Have a nice day ☺️

**Comment by mikolmogorov** [comment]
Hi,

1. Yes, the drawing is correct.
2. Yes, the hypothesis is that the blue repeat (edge/contig 4) is repeated multiple times (e.g. like a very long tandem repeat). I estimated the multiplicity based on the data from assembly_info.txt that you sent: contig_4 has ~10x more depth of coverage than the rest of the genome (940 to 84). As I understand, you are saying that the coverage is in fact 1200x in the gfa file? I think that should be a more accurate estimate, because the coverage after polishing (that is output to assmebly_info) was capped to 1000x in the previous Flye versions (won't be in the next release). Thus, the number of copies weould be roughly 1200 / 84.

**Comment by RxLoutre** [comment]
Alright thank you a lot for your help :)
