### ISSUE TITLE
`short_disj` branch questions

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#392]
Hi Mikhail,

I tried out the `short_disj` branch on some short nanopore reads with some reasonable success, possibly better than miniasm-based approaches or Canu. I was wondering:
1. Is this branch still planned to get integrated into a release version?
2. Are there downsides to this branch if used on long reads like the release Flye?

Thanks,
Sam

**Comment by mikolmogorov** [comment]
Hi Sam,

1. Yes, we're planning to integrate it into the next release (probably as an extra command line option).
2. Theoretically, should not be any significant differences for ONT, but I haven't extensively tested it yet, so everything is possible. It is possible that this mode might add a few extra assmebly gaps because of stricter chimera filters.

**Comment by schorlton** [comment]
Amazing, thanks!

**Comment by mikolmogorov** [comment]
Now fully incorporated in Flye 2.9
