### ISSUE TITLE
Using --asm_coverage with the --meta flag

### ISSUE THREAD

**Issue by dominikmerges** [fenderglass/ABruijn#396]
Hi,

many thanks for your developing this great tool. I have a quick question: Is there any thought on including the asm-coverage option in the --meta assembly mode? 

We try to assemble lichen metagenomes from PacBio CLR subreads (up to 450 GB) and run out on memory on our High Ram machines (64 cores, 900gb ram). We were thinking that the asm-coverage option would help out, but it seems not to be implemented.

Many thanks and cheers,
Dominik

**Comment by mikolmogorov** [comment]
Hi Dominik,

`--asm-coverage` is not very sophisticated - it simply samples top X longest reads to achieve the desired coverage. It does not make much sense for metagenomes, since the size is unknown, and the coverage is variable.

You can certainly downsample your reads manually and this should help with memory usage, at a cost of possibly missed low abundance species. 

Mikhail
