### ISSUE TITLE
Subassembly mode query

### ISSUE THREAD

**Issue by Imogen-D** [fenderglass/ABruijn#454]
Hi,

I am a relative beginner to bioinformatics. I have assembled 5 30Mbp genomes (of the same species, but different isolates) using nanopore reads with Flye and found really great results. I am now attempting to produce a pangenome for downstream analysis and wondering of the best way to continue. One aim is to identify core and accessory genomic regions by post-assembly mapping of initial assemblies onto this pangenome. There appears to be two main courses of action with Flye (although I understand its not designed for pangenomes!) - I am trying both to compare results but am wondering whether you have insight from an algorithmic perspective.

Using the --subassemblies flag, although now depreciated, with my (polished) genomic assemblies. I am assuming this will create a fairly contiguous pangenomic sequence how am unsure about how this copes with similar but non-identical contigs. I am worried about loosing too much information. Do you imagine this will be improved by masking repeats? One initial test (with masking) stated there were no overlaps.

Alternatively, I am planning on giving all nanopore reads from all 5 genomes to Flye. This intuitively seems like the best way to keep all information. I am thinking that the inclusion of the --meta flag would not be recommended here as I am aiming for a contiguous assembly - however I do still want to keep contigs that may be of lower coverage (i.e. just found in one isolate as part of the 'accessory' genome). My initial test (with the --meta flag) produced an assembly within expected limits but relatively discontiguous.

Thanks for your time and a great software.

**Comment by mikolmogorov** [comment]
Hi,

1. The best strategy would be to assemble all isolates separately and then analyse the pangenome. If you are just interested in homology between the genomes, multiple sequence alignment with SlibeliaZ might be a good start (https://github.com/medvedevgroup/SibeliaZ). An alternative way would be to build a pangenome graph and analyze it. Take a look at the methods that are used by the HPRC consortium: vg (https://github.com/vgteam/vg), minigraph (https://github.com/lh3/minigraph), PGGB (https://github.com/pangenome/pggb). 

2. `--subassemblies` or assembling all genomes together with `--meta` is another way to build pagenome graph, but I would not recommend it because you are loosing the information how each genome is traversing this graph (and methods described above should retain it). But it is a valid way, and if you visualize the graph from your meta assembly you should be able to see bubbles/tangles that correspond to variations between your isolates (and cause fragmentation).
