### ISSUE TITLE
Incorrect haplotype polishing?

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/ABruijn#500]
Hi,

This issue is related to the `--polish-haplotypes` subcommand of the `--polish-target` command in the Flye version used by HapDup. Now, given a region, I have the following haplotypes from HapDup (from top to bottom: haplotype 1, haplotype 2 and haploid assembly straight from Flye):
![flye_hap_polish1](https://user-images.githubusercontent.com/1068338/165124502-5acbe76c-ac5c-434d-bd07-c99eeaf6a86f.PNG)
The screenshot is centered on this one SNP on haplotype 2 (middle track) which is incorrect. I went back to the (Margin) phased reads mapped to the haploid assembly:
![flye_hap_polish2](https://user-images.githubusercontent.com/1068338/165124598-c6779e2f-4fd4-4809-a1c5-fe5e384f57ce.PNG)
Screenshot again is centered on the same SNP. It makes no doubt here that something went wrong with the phasing but if we put this aside, the blue reads are the ones used to polish the haploid assembly for haplotype 2: coverage over this region is 3 reads and they all have a different base at this location, only one of them supporting the SNP output in haplotype 2. Any idea what is happening here?

Thanks,
Guillaume

**Comment by mikolmogorov** [comment]
Hi,

I think the reason for that is that hapdup is actually using unphased reads to polish, in addition to either of the haplotypes. 

This is an old strategy we went with, because we expect some regions to be unphased. But now you can actually try only using phased reads for polishing, and regions with no phased reads should just be left untouched.

If you are able to modify hapdup code, here is the line to change (remove "0," from `--polish-haplotypes`): https://github.com/fenderglass/hapdup/blob/main/hapdup/main.py#L222

Let me know if that makes your assemblies better in general, it might eventually make sense to make this a default option.

Best,
Mikhail

**Comment by GuillaumeHolley** [comment]
Just realizing I left this issue open without an answer, sorry about that. Thanks for the feedback!
