### ISSUE TITLE
How to generate custom contigs from assembly graph

### ISSUE THREAD

**Issue by lautimothy** [fenderglass/ABruijn#526]
Hello,

Please see attached picture for the assembly subgraph in question: 4 separate contigs (814, 749, 949, 811) were outputted by Flye.  But is it safe to assume that the complete path is 814,-949,-749,-949,811 ?

Even if so, however, from the 30-contigger folder, it seems the output contigs are not just simple concatenation of the edges of the graphs.  I am assuming Flye did something extra to make sure the edge boundaries are correct, is there a way for me to generate a contig for the whole path in a similar way?

![graph_sample](https://user-images.githubusercontent.com/7570957/185148435-c6694219-8965-460a-a82f-5450796bf717.png)

thank you for the great assembler,
Tim

**Comment by mikolmogorov** [comment]
Hi Tim,

Sorry for the late response. I think Bandage has the functionality to modify assembly graph - I would give it a try.

Flye does not solve such cases automatically because sometimes assembly graphs may have missing connections, which may lead to false decisions based on graph topology. In this particular case, it seems strange to me that edge `749` has lower coverage that the long edges.

**Comment by lautimothy** [comment]
Thanks for the recommendation and explanation, Mikhail. I will checkout Bandage.

**Comment by mikolmogorov** [comment]
Marked as answered, but feel free to follow up if you have more questiosns!
