### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by hp2048** [fenderglass/ABruijn#55]
Hi
I am trying to assemble 3 mammalian genomes (~35-55x coverage, genome size ~3GB) using Flye. My attempts are failing due to memory related issues (core dumps). We have access to ~1Tb RAM machines. I have noticed that memory footprint is being investigated by your team. I was just wondering if there were any updates available? We are planning to to have these genomes at ~100x coverage ultimately. It would be most useful if you can let us know what is the progress being made regarding memory footprint.

I work with Dr. Yu Lin from the Australian National University and he is collaborating with us on this project.

We are happy to assist in the further development of Flye if you can point us in the right direction regarding the development plan.

Kind regards
Hardip

**Comment by mikolmogorov** [comment]
Hi Hardip,

We were working on some memory/performance optimizations recently, but the first assembly stage (generating draft contigs) remains a bottleneck, unfortunately. However, we were able to assemble human genomes with ~700Gb of RAM - so your mammalian assemblies theoretically should work too. Here is a couple of tips that hopefully should help:

1. Memory usage scales linearly with coverage. I recommend to try to assemble the longest 30x of reads first. You then should be able to use the full set of reads for repeat resolution, by re-running the repeat resolution stage (by running with '--resume-from repeat').

2. I assume you mammalian genomes have size ~3Gb. Try to run Flye with the genome size estimate of 1.5Gb, instead of 3Gb. This is mainly because for a mammalian genome of size 3gb there is roughly 1.5bb of unique 17-mers (because of the repeat content). This should also save you ~100Gb of RAM.

**Comment by mikolmogorov** [comment]
FYI, we have just pushed an updated version 2.3.6b into the 'flye' branch (it is not in the releases yet). It now consumes ~30% less memory on large genomes, and you can further decrease it by setting '--asm-coverage' argument, which controls how much sequence will be used in the initial contig assembly (I recommend to set it to 30 for your high-coverage assemblies).

**Comment by hp2048** [comment]
Thank you so much Mikhail. This will be life saver for us. I will stay in touch if I run into problems.

Cheers
Hardip
