### ISSUE TITLE
Minimum length of reads and overlaps

### ISSUE THREAD

**Issue by dmckeow** [fenderglass/ABruijn#564]
Hello!
I am working with ONT data typically with an average read length of around 400 bp (we are sequencing cDNA from RNA metagenomes/transcriptomes).
This means that we need to set a minimum overlap size that is much less than the allowed range set by Flye-2.9.1 (1000-10000 bp).
In addition, our reads are also mostly below the minimum length that Flye will allow (1000 bp), so this issue is also about the minimum read length AND minimum overlap allowed by Flye.
As a result, Flye-2.9.1 will not run on our data:

flye: error: argument -m/--min-overlap: value should be in the range [1000, 10000]

Is there a workaround for this, such as a way to override the minimum read and overlaps settings?
And if not, is there a possibility that in future Flye will be able to run on shorter ONT reads?
Thanks
Dean

**Comment by katievigil** [comment]
@fenderglass is there anywhere in the output where I can get the mean and median contig sizes (nt)?

**Comment by mikolmogorov** [comment]
@dmckeow due to the way Flye was designed it will not work with overlaps smaller than 1000bp. It will be difficult to change and I am not planning to reduce it currently. Shorter ONT reads is indeed potentially interesting area of development, other assemblers (like minimap or Canu) may be better suited for that.

@lucyintheskyzzz I don't think Flye provides this output.
