### ISSUE TITLE
Question on polishing output

### ISSUE THREAD

**Issue by FabianDK** [fenderglass/ABruijn#586]
Dear authors,

I am running flye with the ```stop-after contigger``` option, and then I run the flye polishing with --polish-target contigs.fasta from the contigger step and the raw reads.

This produces a file named ```polished_1.fasta``` and my question is whether this file is supposed to be equal to the ```assembly.fa``` the uninterrupted flye command (or the resume option) is creating.

Commands to create polished_1.fasta:
```
flye --nano-hq file.fq.gz -g 2.4g -o assemblies/flye/sample_A -t 30 --stop-after contigger
flye --nano-hq file.fq.gz -g 2.4g --polish-target contigs.fasta -o assemblies/flye/sample_A/polishing -t 16
```

In my example, the assembly.fa output has 1666 contigs, while polished_1.fasta has 2325.

Thanks,
Daniel

**Comment by mikolmogorov** [comment]
Hi Daniel,

Some differences are expected, because assembly polishing stage (as opposed to `--polish-target`) applies additional coverage-based filtering to polished contigs. The additional contigs in `polished_1.fasta` are likely to have very few (or none) reads aligned to them.

Hope this helps, let me know if you have other questions.
Misha
