### ISSUE TITLE
Parameters for substantial Nanopore metagenomic datasets

### ISSUE THREAD

**Issue by tnn111** [fenderglass/ABruijn#598]
I have a substantial Nanopore metagenomic dataset. It's ~500 Gbases now and it's possible that I might add to it. Most of it was generated using R10.4.1 flow cells with dorado-sup basecalling with the rest being from R10.4 flow cells.

Does anyone have experience with this kind of dataset? My main interest is in getting solid circular genomes out. I've been playing with filtering the data to eliminate reads with low Q scores and it does bring out a few more complete genomes, but I'm wondering if anyone has suggestions for parameter settings that might be modified.

Thanks!

**Comment by mikolmogorov** [comment]
I know that people have been playing with `--extra_params min_read_cov_cutoff=XX`. This sets up a hard threshold for minimum edge coverage, everything below with be discarded. It is 3 by default (so maximizing recovery of rare strains), but if you are only interested in assembling the most abundant organisms, it makes sense to try increasing it.

To try different values and save time, you can actually restart from the repeat stage, since this parameter does not affect the disjointig assembly.
