### ISSUE TITLE
Contigs shorter than expected from graph_path

### ISSUE THREAD

**Issue by dalofa** [fenderglass/ABruijn#610]
Recently, while assembling a large number of _Streptomyces_ genomes from nanopore data, we have observed a few cases where Flye outputs contigs that are shorter than we expect from the GFA. 

**An example:**

Running Flye with 5 iterations of polishing returns:

```assembly_info.txt
#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_2	8834926	120	N	N	1	*	*,1,2,-1,*
```

The length of the edges from GFA:
edge_1	78646 nt
edge_2	8722953 nt

In this case we assume that contig 2 would be 2 * edge_1 + edge_2= 2*78646 nt+ 8722953 nt = 8880245 nt in length. However, it is in fact 8880245 nt -8834926 nt = 45319 nucleotides shorter as reported in the assembly_info.txt file. Specifically, it seems this behavior is related to the joining of the inverted repeats (edge_1), where one of the repeats does not contain the full 78 kb sequence as we have had issue identifying the inverted repeats using BLAST (which have worked fine in other cases).

**No polishing**
We suspected that this behavior was related to polishing but running Flye with no polishing returns a similar result:

```assembly_info.txt
#seq_name       length  cov.    circ.   repeat  mult.   alt_group       graph_path
contig_2        8821179 112     N       N       1       *       *,1,2,-1,*
contig_1        78878   295     N       Y       3       *       *,1
```
The length of the edges:
edge_1: 78878 nt
edge_2: 8710584 nt

Again we expect contig 2 to be  2 * 78878 nt + 8710584 nt = 8868340 nt in length given its graph_path but it is instead 8868340 nt - 8821179 nt =47161 nt shorter than expected.
 
Currently we have seen this in two assemblies and can provide more information regarding this.

I have attached the flye.log-files from the two assemblies described.
[flye.log.log](https://github.com/fenderglass/Flye/files/11905620/flye.log.log)
[flye.nopolish.log](https://github.com/fenderglass/Flye/files/11905621/flye.nopolish.log)

**Comment by mikolmogorov** [comment]
Hi @dalofa 

Flye is being cautious here. Although from the graph it is apparent that the sequence of the contig should be `1,2,-1`, the current algorithm will only extend the unique sequence into repeat using direct evidence from reads. Since you are unlikely have reads longer than 78kb (assuming it is not UL), Flye will take the longest reads that it can anchor to the unique sequence of `2` in this case. Even though the structure is obivious in this case, it is hard to come up with a general rule that will not occasionally make misassemblies in this situation.

I think the current solution may be to manually join the unitig sequences from `assembly_graph.gfa` and add another round of polishing using `--polish-target`.

Hope this helps,
Misha

**Comment by mikolmogorov** [comment]
Marking as resolved.
