### ISSUE TITLE
co-assemble samples with different read depth

### ISSUE THREAD

**Issue by wn835166087** [fenderglass/ABruijn#645]
Hi,
I have two batch of metagenomic samples that i want to co-assemble them. One batch was sequenced using MinION R9.4.1 + rapid kit (after QC: Q>7, len>200), the other using MinION R10.4.1 + ligation (after QC: Q>10, len > 200). Both of them were base called by Guppy -sup mode. As the rapid kit yield lower sequencing depth, and the R9.4.1 yield lower average Q, would those impact the assembly if I co-assemble reads from two batch? Any suggestions? Thank you a lot!

**Comment by mikolmogorov** [comment]
You can mix the two datasets, which should give you a better assembly, but confuse the polisher. You may want to do a separate round of polishing with just R9 (since it has the largest coverage).

I would also compare a mixed assembly against separate R9 and R10 assemblies to see how much value R10 is adding in this context.

**Comment by wn835166087** [comment]
> You can mix the two datasets, which should give you a better assembly, but confuse the polisher. You may want to do a separate round of polishing with just R9 (since it has the largest coverage).
> 
> I would also compare a mixed assembly against separate R9 and R10 assemblies to see how much value R10 is adding in this context.

Hi,
I tested the assemble separately, and it seems that assembling separately works better. Thank you.

**Comment by mikolmogorov** [comment]
Great! Marking this as resolved, but feel free to follow up if you have any other questions.
