### ISSUE TITLE
Gaps in the assembly

### ISSUE THREAD

**Issue by yeban** [fenderglass/ABruijn#81]
Hello,

I am seeing short stretches of 'N's (gaps) in my assembly. The assembly was generated from 20x nanopore data using flye 2.3.7. I am looking to understand at what stage of the assembly process do the Ns get added. Is it from the repeat resolution step, or is that flye has some kind of scaffolding step similar to SPADES which adds the Ns?

**Comment by mikolmogorov** [comment]
Hi,

Yes, there is scaffolding step - but it is based on the graph structure, rather than read information (as in SPAdes). If you prefer to work with contigs only - you can use the sequences from file `40-polishing/polished_1.fasta` (where `_1` would be the number of polishing iterations).

**Comment by yeban** [comment]
Thanks.

**Comment by bbalog87** [comment]
Hi Mikhail,

Could you briefly explain how scaffolding is done with Flye? I didn't find these details in your  latest Nature Biotechnology paper. Which repeats graph information do you put  together? How do you  link and order  contigs into scaffolds as output in the assembly.fasta file.  How reliable do you think these scaffolds are since no reads information are taken into consideration?

Thanks,
Julien

**Comment by mikolmogorov** [comment]
Hi Julien,

It is a very simple algorithm: for each unique edge, Flye checks all possible outgoing paths through repetitive nodes. If all these paths lead to a single unique edge, then a connection is made.

Here is an example. In this case, edge -2 will be scaffolded with 3. On the other hand, 1 might be continued either to -2 or -4 (through -6). Because of this ambiguity,  Flye won't make the connection.

In our experience, scaffold connections are usually reliable. But theoretically, false connections are possible, for example through a terminal repeat between two unrelated viruses.

Hope this helps!
Mikhail

![assembly_graph gv](https://user-images.githubusercontent.com/2475380/62076170-d03bd300-b1fb-11e9-9e17-5a7575a5e187.png)

**Comment by bbalog87** [comment]
Thank you Mikhail! The figure is really helpful.
Best,
Julien
