### ISSUE TITLE
--genome-size option for metagenome

### ISSUE THREAD

**Issue by qinglong89** [fenderglass/ABruijn#84]
Hi Mikhail,

I am trying to use flye for assembling contigs of "concatenated individual assemblies" generated from shotgun metagenome (Illumina reads; megahit). I do not have long reads. I am trying to reduce the redundancy of contigs for downstream analysis. Co-assembly of all shotgun metagenomes is CPU- and RAM-intensive, that is why I choose individual assemblies since I got more than 1000 shotgun metagenomes.

Based on your documentation, -g option must be used, but it becomes difficult for me to figure out the estimated genome size of "concatenated individual assemblies". I used the size of the concatenated file, but I guess it would be appropriate. 

Any suggestions?

Here s my flye run:
flye --subassemblies all_final.contigs.HeaderRenamed.fa --threads 20 --meta -g $(grep -v ">" all_final.contigs.HeaderRenamed.fa | wc | awk '{print $3-$1}') --min-overlap 1000 -o flye_output_EstimatedSize &

Thanks.

Qinglong

**Comment by mikolmogorov** [comment]
Hi,

You can provide a rough estimate of the expected assembly size - in `subassemblies` mode the algorithm is not very sensitive to this parameter in fact. I am also not sure is `--meta` is a good choice (since you merging assemblies, but not reads) - I would try both with and without and see which one works better.
