### ISSUE TITLE
min-overlap limit

### ISSUE THREAD

**Issue by MichelMoser** [fenderglass/ABruijn#92]
Hello, 

Is there a reason the have an upper limit to min-overlap? 
I am assembling fish genomes with nanopore read N50's of 20 - 30 Kb, so i think increasing the min-overlap above 10K could be benefitial for the assembly. 

Thanks, 
Michel

**Comment by mikolmogorov** [comment]
Hi,

Flye selects minimum overlap as reads N90 - this is usually a balanced choice between assembly graph complexity and a chance of having coverage gaps. Because Flye simplifies the graph using bridging reads, minimum overlap does not "limit" your repeat resolution capabilities in most cases. What is you read coverage / N90? If you are interested in the effect of this parameter, I suggest to first check the automatically selected value and then try to manually increase it (say, to 7k) and see if there is an improvement.

Best.
Mikhail

**Comment by MichelMoser** [comment]
Hi, 

I just received results from two flye runs of our smallest genome (700 Mb) with 55x nanopore coverage,  read N50/N90 of 20522 / 6789 bp: 


`-m 5000 ("auto seletced")`
sum = 728152355, n = 2883
ave = 252567.59
largest = 10987219
N50 = 1029059, n = 168

`-m 10000`
sum = 734911571, n = 2638
ave = 278586.65
largest = 10962916
N50 = 1372550, n = 137

Looks like -m 10000 has slightly better stats. 

We work with a couple of genomes, from 1 Gb to 3 Gb, most of them have nanopore data in the 45x range and N90 between 6 and 8 Kb. 
I am asking because we wont be able to play with parameters for the larger genomes as assembly will run for a whole week. 

Best, 
Michel

**Comment by mikolmogorov** [comment]
Thanks for running the tests! It does seem there is an improvement - which is a bit puzzling for me. Are these genomes repeat-rich? I can see that if a genome contains a lot of low complexity repeat sequence, then the graph might become too tangled to analyze - so it might be what is happening here. It also could be interesting to make one more run with an intermediate min overlap value (7.5k) to see the dynamics (if it does not take too much of your resources).

So as you noticed, the automatic selection has an upper limit of 5k - because we previously observed some strange effects with larger values. But maybe with the newer data it makes sense to increase it. For the big runs, I would still start with N90 (but you can set it manually to override the 5k limit) - since this option was widely tested. This way you will also see how long does the assembly take and maybe you will be able to test other parameters.

Also FYI, the 10k manual limit could be changed here: `flye/main.py, line 656`
